'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebForm5

    '''<summary>
    '''CustomerInfoPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomerInfoPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''CompanyNameDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompanyNameDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''EmployeeNameDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmployeeNameDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RequiredDateTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequiredDateTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShipViaDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShipViaDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ShipNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShipNameTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShipAddressTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShipAddressTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShipCityTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShipCityTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShipRegionTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShipRegionTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShipPostalCodeTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShipPostalCodeTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShipCountryTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShipCountryTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''StartOrderButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StartOrderButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ConfirmationLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConfirmationLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ProductInformationPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProductInformationPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ProductDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProductDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''QuantityTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuantityTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''OrderNumberTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderNumberTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DiscountTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DiscountTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AddItemButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddItemButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ErrorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ErrorLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''OrderedItemsPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderedItemsPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''OrderGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OrderGridView As Global.System.Web.UI.WebControls.GridView
End Class
